api_platform:
    title: 'Captain Coaster API'
    description: 'Welcome to Captain Coaster API! Please contact us to get support.'
    version: '1.0.3'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    http_cache:
        public: true
    defaults:
        stateless: true
        cache_headers:
            max_age: 3600
            shared_max_age: 3600
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    swagger:
        api_keys:
            key:
                name: 'Authorization'
                type: 'header'
    formats:
        jsonld: ['application/ld+json']
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
